repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.285
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: mixed-line-ending
      - id: name-tests-test
        args: ['--django']
      - id: check-json
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        exclude_types: [json]
  - repo: https://github.com/marco-c/taskcluster_yml_validator
    rev: v0.0.10
    hooks:
      - id: taskcluster_yml
  - repo: https://github.com/MozillaSecurity/orion
    rev: v0.0.7
    hooks:
      - id: orion_ci
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: tox -e mypy --
        language: system
        require_serial: true
        types: [python]
      - id: pylint
        name: pylint
        entry: tox -e pylint --
        language: system
        require_serial: true
        types: [python]

default_language_version:
  python: python3
